apiVersion: skaffold/v1
kind: Config
metadata:
  name: check-resource-access
deploy:
  kubectl:
    manifests:
    - k8s/check-resource-access.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/check-resource-access
  local: {}
